config/routes.rb
Rails.application.routes.draw do
  get 'messages/index'
  post '/top/guest_sign_in', to: 'top#new_guest'
  devise_for :users
  get 'top/index'
  root to: "top#index"
  resources :attendances, only: [:index, :new, :create]
  resources :prints, only: [:index, :new, :create]
  resources :rooms, only: [:index, :new, :create, :destroy] do
    resources :messages, only:[:index, :create]
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :presence
  belongs_to :breakfast
  belongs_to :bath
  belongs_to :temperture

  with_options numericality: { message: 'Select' } do
    validates :presence_id
    validates :breakfast_id
    validates :bath_id
    validates :temperture_id
  end

  belongs_to :user
end

app/models/bath.rb
class Bath < ActiveHash::Base
  self.data = [
    { id: 1, name: '入った' },
    { id: 2, name: '入らなかった' }
  ]

  include ActiveHash::Associations
  has_many :attendances
end

app/models/breakfast.rb
class Breakfast < ActiveHash::Base
  self.data = [
    { id: 1, name: '沢山食べた' },
    { id: 2, name: '少しだけ食べた' },
    { id: 3, name: '全然食べなかった' }
  ]

  include ActiveHash::Associations
  has_many :attendances
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user
  has_one_attached :image

  validates :content, presence: true, unless: :was_attached?

  def was_attached?
    image.attached?
  end
end

app/models/presence.rb
class Presence < ActiveHash::Base
  self.data = [
    { id: 1, name: '出席' },
    { id: 2, name: '欠席' }
  ]

  include ActiveHash::Associations
  has_many :attendances
end

app/models/print.rb
class Print < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validates :title, presence: true
  validates :text, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  has_many :room_users
  has_many :users, through: :room_users, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :name, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/temperture.rb
class Temperture < ActiveHash::Base
  self.data = [
    { id: 1, name: '平熱' },
    { id: 2, name: '37.0~37.4度' },
    { id: 3, name: '37.5度以上' }
  ]

  include ActiveHash::Associations
  has_many :attendances
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :name
    validates :child_name
  end

  has_many :attendances
  has_many :prints
  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :child_name])
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!

  def index
    @attendances = Attendance.includes(:user).order('created_at DESC')
  end

  def new
    @attendance = Attendance.new
  end

  def create
    @attendance = Attendance.new(attendance_params)
    if @attendance.valid?
      @attendance.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def attendance_params
    params.require(:attendance).permit(:presence_id, :breakfast_id, :bath_id, :temperture_id).merge(user_id: current_user.id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def index
    @message = Message.new
    @room = Room.find(params[:room_id])
    @messages = @room.messages.includes(:user)
  end

  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.new(message_params)
    if @message.save
      redirect_to room_messages_path(@room)
    else
      @messages = @room.messages.includes(:user)
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end
end

app/controllers/prints_controller.rb
class PrintsController < ApplicationController
  before_action :authenticate_user!

  def index
    @prints = Print.includes(:user).order('created_at DESC')
  end

  def new
    @print = Print.new
  end

  def create
    @print = Print.new(print_params)
    if @print.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def print_params
    params.require(:print).permit(:title, :text, :image).merge(user_id: current_user.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to rooms_path
    else
      render :new
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to rooms_path
  end

  private

  def room_params
    params.require(:room).permit(:name, user_ids: [])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end

  def new_guest
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'guest'
      user.child_name = 'rukia'
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/attendances/index.html.erb
<div class="atten-b">
  <div class="atte-title">
  <h1 class>出欠一覧</h1>
  </div>
  
    <div class="atte-contents">
    <table border="1">
      <tr>
        <th>名前</th><th>出欠</th><th>お風呂</th><th>朝ご飯</th><th>体温</th><th>投稿時間</th>
      </tr>
      <% @attendances.each do |attendance| %>
      <tr>
        <td><%= attendance.user.name %></td>
        <td><%= attendance.presence.name %></td>
        <td><%= attendance.bath.name %></td>
        <td><%= attendance.breakfast.name %></td>
        <td><%= attendance.temperture.name %></td>
        <td><%= l attendance.created_at %></td>
      </tr>
      <% end %>
    </table>
    </div>
  
</div>

app/views/attendances/new.html.erb
<div class="box">
  <div class="box-inner">
    <div class="form__wrapper">
      <h2 class="page-heading">出欠フォーム</h2>
        <%# 部分テンプレートでフォームを表示する %>
        <%= form_with(model: @attendance, local: true) do |f| %>

          <div class="box-email">
            <%= f.label :title, "出欠" %><br />
            <%= f.collection_select(:presence_id, Presence.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
          </div>

          <div class="box-email">
            <%= f.label :title, "朝食" %><br />
            <%= f.collection_select(:breakfast_id, Breakfast.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
          </div>

          <div class="box-email">
            <%= f.label :title, "お風呂" %><br />
            <%= f.collection_select(:bath_id, Bath.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
          </div>

          <div class="box-email">
            <%= f.label :title, "体温" %><br />
            <%= f.collection_select(:temperture_id, Temperture.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
          </div><br>

          <div class="box-login">
            <%= f.submit "送信する" %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RenrakuApp</title>
    <meta name="description" content="先生と保護者のコミュニケーションを円滑にする連絡帳アプリです。">
        <link rel="icon" type="image/png" href="images/favicon.png">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# CSS %>
    <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+1p" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_main_chat.html.erb
<div class="chat-top">
  <div class="left-header">
    <div class="chat-title">
    <%= @room.name %>
    </div>
  </div>
  <div class="right-header">
    <div class="chat-end">
      <%= link_to "チャットを終了する", room_path(@room), method: :delete %>
    </div>
  </div>
</div>

<div class="chat-main">
  <%= render partial: 'message', collection: @messages %>
</div>

<%= form_with model: [@room, @message], class: 'form', local: true do |f| %>
<div class="chat-bottom">
  <div class="form">
    <%= f.text_field :content, class: 'form-message', placeholder: 'type a message' %>
    <label class="form-image">
      <span class="image-file">画像</span>
      <%= f.file_field :image, class: 'hidden' %>
    </label>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
<% end %>

app/views/messages/_message.html.erb
<div class="message-box">
  <div class="message-upbox">
    <div class="message-name">
      <!-- 投稿したユーザー名情報を出力する -->
      <%= message.user.name %>
    </div>
    <div class="message-time">
      <!-- 投稿した時刻を出力する -->
      <%= l message.created_at %>
    </div>
  </div>
  <div class="message-downbox">
    <div class="message-text">
      <!-- 投稿したメッセージ内容を記述する -->
      <%= message.content %>
    </div>
    <%= image_tag message.image.variant(resize: '500x500'), class: 'message-image' if message.image.attached? %>
  </div>
</div>

app/views/messages/_side_bar.html.erb
<div class="side-top">
  <div class="name-box">
    <a href="#">
    <%= current_user.name %>
    </a>
  </div>
  <div class="chat-make">
    <%= link_to "チャットを作成する", new_room_path %>
  </div>
</div>
<div class="rooms">
  <% current_user.rooms.each do |room| %>
    <div class="room">
      <div class="room-name">
        <%= link_to room.name, room_messages_path(room) %>
      </div>
    </div>
  <% end %>  
</div>

app/views/messages/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="chat">
    <%= render "main_chat" %>
  </div>
</div>

app/views/prints/index.html.erb
<div class="pri-main">
  <% @prints.each do |print| %>
  <div class="pri-container">
    <div class='pri-info'>
      <h3 class='pri-title'>
        <%= print.title %>
      </h3>
      <div class='pri-time'>
        <span><%= l print.created_at %><br></span>
      </div><br>
      <div class='pri-text'>
        <span><%= print.text %><br></span>
      </div>
    </div>   
    <% if print.image.attached? %>
      <div class='pri-img-content'>
      <%= image_tag print.image.variant(resize: '500x500') %>
      </div>
      <% end%>
      <br><br>
      </div>
    <% end %>
  </div>

app/views/prints/new.html.erb
<div class="box">
  <div class="box-inner">
    <div class="form__wrapper">
      <h2 class="page-heading">お知らせ投稿</h2>
        <%= form_with model: @print, local: true do |f|%>
          <div class="box-email">
            <%= f.label :title, "題名" %><br />
            <%= f.text_field :title, class: "text-box" %>
          </div>

          <div class="box-email">
            <%= f.label :text, "本文" %><br />
            <%= f.text_area :text, class: "text-area" %>
          </div>

          <div class="box-email">
            <%= f.label :image, "画像" %><br />
            <%= f.file_field :image, id:"print-image"%>
          </div>
          <div class="right-img-upload">
          <div id="image"></div>
          </div>

          <div class="box-login">
            <%= f.submit "投稿する" %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <%= render "messages/side_bar" %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="box">
  <div class="box-inner">
    <h1>新規チャットルーム</h1>
    <%=form_with model: @room, local: true do |f|%>
      <div class="box-email">
        <%= f.label :name , "チャットルーム名" %> <em></em><br />
        <%= f.text_field :name, autofocus: true, placeholder: 'チャットルーム名を入力してください' %>
      </div>

      <div class="box-email">
        <%= f.label :child_name, "チャットメンバー" %> <em></em><br />
        <select name="room[user_ids][]">
          <option value="">チャットするユーザーを選択してください</option>
          <% User.where.not(id: current_user.id).each do |user| %>
            <option value=<%=user.id%>><%= user.name %></option>
            <% end %>
        <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
        </select>
      </div>
      <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/top/index.html.erb
<div id="container" >
    <div class="header">
        <div class="logo">
          <span class="logo__world">Renraku!</span>
        </div>
      <div class="login">
        <%# <div class="nav__btn"> %>
          <%= link_to 'ゲストログイン', top_guest_sign_in_path, method: :post, class: "nav__btn" %>
        <%# </div> %>
        <% if user_signed_in? %>
        <div class="nav__btn">
          こんにちは、
        <%= link_to current_user.name + "さん", "#", class: "subtitle" %>
        </div>
        <div class="nav__btn">
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "subtitle" %>
        </div>
        <% else %>
        <div class="nav__btn">
        <%= link_to '新規会員登録', new_user_registration_path, class: "subtitle" %>
        </div>
        <div class="nav__btn">
        <%= link_to 'ログイン', new_user_session_path, class: "subtitle" %>
        </div>
        <% end %>
      </div>
    </div>
    
  <div class="hamburger-menu">
    <input type="checkbox" id="menu-btn-check">
    <label for="menu-btn-check" class="menu-btn"><span></span></label>
    <div class="menu-content">
      <ul>
          <li>
              <a href="https://docs.google.com/forms/d/e/1FAIpQLSdu_OQl4cJPiemyEF9rMOyl8b5G06Jp02pK0Xc_ISqVa8s1yQ/viewform?usp=sf_link" width="100%" height="1301" frameborder="0" marginheight="0" marginwidth="0">お問い合わせ</a>
          </li>
          <li>
              <a href="../prints">お知らせ一覧へ</a>
          </li>
          <li>
              <a href="../rooms">メッセージルームへ</a>
          </li>
          <li>
              <a href="../attendances/new">連絡帳へ</a>
          </li>
          <li>
              <a href="../prints/new">お知らせ投稿へ</a>
          </li>
          <li>
              <a href="../attendances">出欠一覧へ</a>
          </li>
      </ul>
    </div>
  </div>
  <section>
      <div class="inquiry">
          <p>お問い合わせはこちら➡️</p>
          <a href="https://docs.google.com/forms/d/e/1FAIpQLSdu_OQl4cJPiemyEF9rMOyl8b5G06Jp02pK0Xc_ISqVa8s1yQ/viewform?usp=sf_link" width="100%" height="1301" frameborder="0" marginheight="0" marginwidth="0" class="btn">お問い合わせフォームへ
          </a>
      </div>
  </section>
  <div id="home">
    <div class="big-bg">
        <%= image_tag "main-bg.jpeg" %>
    </div>
      <div class="home-set">
              <div class="page-title">
                  <h2>毎日の連絡をもっと簡単に</h2>
                  <p>スマホで手軽に連絡しよう!</p>
              </div>
              <div class="inquiry__nav">
                  <p>お問い合わせはこちら➡️</p>
                  <a href="https://docs.google.com/forms/d/e/1FAIpQLSdu_OQl4cJPiemyEF9rMOyl8b5G06Jp02pK0Xc_ISqVa8s1yQ/viewform?usp=sf_link" width="100%" height="1301" frameborder="0" marginheight="0" marginwidth="0" class="btn">
                  <div class="btn">お問い合わせフォームへ</div></a>
              </div>
              <div class="app__nav">
                  <p>アプリダウンロード➡️</p>
                  <div class="app-img">
                  <%= link_to image_tag("app-img1.png", class:"app__img"), "/" %>
                  <%= link_to image_tag("app-img2.png", class:"app__img"), "/" %>
                  </div>
              </div>

              <div class="home-btn">
                  <p>会員登録はこちら</p>
                  <div class="nav__btn">
                    <%= link_to '新規会員登録', new_user_registration_path, class: "subtitle" %>
                  </div>
              </div>
          </div>    
      </div>
  </div>
  <section class="howto">
      <div class="howto__content">
        <div class="howto__title">
        <h3><span>ご利用方法</span>
        </h3>
        </div>
        <div class="howto__body">
          <div class="howto__img">
          <%= image_tag "middle-image.jpg" %>
          </div>
          <div class="howto__text">
              <p>
                  まずは「レンラク！」アプリに新規登録下さい。登録後
                  は、ログインしていただければ、連絡帳機能を使用する
                  ことができます。
                  連絡帳フォームを送信すれば先生がすぐ確認できます。
                  朝の忙しい時間をゆっくり過ごす助けになるアプリケーションです。
              </p>
          </div>
        </div>
      </div>
  </section>
  <section class="service">
      <div class="service__content">
        <div class="service__title">
        <h3><span>レンラク！のサービス紹介</span>
        </h3>
        </div>
        <div class="service__lower">
            <div class="service__icons">
                <div class="icon-set">
                    <div class="service__icon">
                    <%= image_tag "service-icon1.png" %>
                    </div>
                    <div class="icon-name">
                    <p>連絡帳機能</p>
                    </div>
                </div>
                <div class="icon-set">
                    <div class="service__icon">
                    <%= image_tag "service-icon2.png" %>
                    </div>
                    <div class="icon-name">
                    <p>出欠管理</p>
                    </div>
                </div>
                <div class="icon-set">
                    <div class="service__icon">
                    <%= image_tag "service-icon3.png" %>
                    </div>
                    <div class="icon-name">
                    <p>お知らせ配信</p>
                    </div>
                </div>
                <div class="icon-set">
                    <div class="service__icon">
                    <%= image_tag "service-icon4.png" %>
                    </div>
                    <div class="icon-name">
                    <p>個別メッセージ</p>
                    </div>
                </div>
                <div class="icon-set">
                    <div class="service__icon">
                    <%= image_tag "service-icon5.png" %>
                    </div>
                    <div class="icon-name">
                    <p>写真投稿機能</p>
                    </div>
                </div>
            </div>
            <div class="service__text">
                <p>
                  出欠確認は出欠フォームから入力していただいた後、ボタン一つで送信完了となります。個別にメッセージを送受信する機能も備えております。保育者はお知らせを一斉配信することができます。保護者の方はお知らせをスマホでいつでも確認することができます。
                </p>
            </div>
          </div>
        </div>
      </div>
  </section>
  <div class="social-content">
      <section class="social">
          <div class="social__title">
              <h3><span>このアプリの社会貢献</span></h3>
          </div>
          <div class="social__text">
              <p>
                業務をICT化して、保護者の方と保育者の方、両方の時間を確保することを目的としたアプリケーションです。
              </p>
          </div>
              <div class="social__bottom">
                  <div class="social__iconset">
                      <div class="social__voice">
                        <p><span>保育者の声</span><br>
                            お知らせを手書きで書いていて、時間を取られていた。アプリを使用すると、一斉に送信できるので、子供と過ごす時間が増えました。
                        </p>
                      </div>
                      <div class="social__image">
                            <%= image_tag "social-icon1.png" %>
                      </div>
                  </div>
                  <div class="social__iconset">
                      <div class="social__voice">
                        <p><span>保育者の声</span><br>
                            お知らせを手書きで書いていて、時間を取られていた。アプリを使用すると、一斉に送信できるので、子供と過ごす時間が増えました。
                        </p>
                      </div>
                      <div class="social__image">
                            <%= image_tag "social-icon2.png" %>
                      </div>
                  </div>
              </div>
      </section>
  </div>
      <section class="question">
  <div class="question-content">
          <div class="question__title">
              <h3><span>よくあるご質問</span></h3>
          </div>
          <div class="question__box">
              <div class="question__text">
                  <h4><span>メッセージでは写真も送信できますか</span></h4>
                  <p>
                      文章と一緒に写真も送信していただけます。もちろん文章のみの送信も可能です。
                  </p>
              </div>
          </div>
          <div class="question__box">
              <div class="question__text">
                  <h4><span>スマホでアプリを使用できますか？</span></h4>
                  <p>
                      スマホにアプリをインストールしていただき、新規登録していただくことで、使用できます。お知らせをいつでも確認することができたり、出欠の連絡もフォームの送信にて簡単に行うことができます。
                  </p>
              </div>
          </div>
          <div class="question__bottom">
          <a href="#" class="question__btn">よくある質問をもっと見る</a><br>
          </div>
          <br>
  </div>
      </section>
<div class="bottom">
        <%= image_tag "bottom-img2.jpeg" %>
    <p>
      コミュニケーションをもっと手軽に、是非”Rennraku＂をご利用下さい。
    </p>
    <a href="https://docs.google.com/forms/d/e/1FAIpQLSdu_OQl4cJPiemyEF9rMOyl8b5G06Jp02pK0Xc_ISqVa8s1yQ/viewform?usp=sf_link" width="100%" height="1301" frameborder="0" marginheight="0" marginwidth="0">
    <div class="bottom__btn">お問い合わせフォームへ</div>
    </a>
</div>
<div class="footer__content">
    <section class="footer">
        <div class="logo">
          <span class="footer__logo">Renraku!</span>
        </div>
        <div class="footer__nav">
            <div class="footer__box">
                <ul>
                    <li>
                        <a href="#">プライバシーポリシー</a>
                    </li>
                    <li>
                        <a href="#">利用規約</a>
                    </li>
                    <li>
                        <a href="#">お問い合わせ</a>
                    </li>
                </ul>
            </div>
            <div class="footer__box">
                <ul>
                    <li>
                        <a href="#">よくあるご質問</a>
                    </li>
                    <li>
                        <a href="#">資料請求</a>
                    </li>
                    <li>
                        <a href="#">会社概要</a>
                    </li>
                </ul>
            </div>
            <div class="footer__box">
                <ul>
                    <li>
                        <a href="#">ご利用方法</a>
                    </li>
                </ul>
            </div>
        </div>
    </section>
</div>
<div class="copyright">
    <p>
      Copyright RenrakuApp 2021.
    </p>
</div>